// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AffectedRouteDTO {
    "route": string;
    "method": string;
}

export interface CodeFlowDTO {
    "message": string;
    "threadFlows": ThreadFlowDTO[] | null;
}

export interface CodeFlowStepDTO {
    "message": string;
    "location": LocationDTO;
    "executionOrder": number;
    "nestingLevel": number;
}

export interface FindingDTO {
    "key": FindingKey;
    "runName": string;
    "toolName": string;
    "ruleId": string;
    "ruleName": string;
    "ruleDescription": string;
    "helpUri": string;
    "message": string;
    "sarifLevel": string;
    "severity": string;
    "disposition": string;
    "comment": string;
    "reviewedAt": string;
    "location": LocationDTO;
    "findingId": string;
    "isReachable": boolean | null;
    "vulnerabilityEvidence": string;
    "affectedRoute": AffectedRouteDTO;
    "codeFlows": CodeFlowDTO[] | null;
}

export interface FindingKey {
    "runIndex": number;
    "resultIndex": number;
}

export interface FindingReview {
    "runIndex": number;
    "resultIndex": number;
    "severity": string;
    "disposition": string;
    "comment": string;
    "reviewedAt": string;
}

export interface GitAuthenticationDTO {
    "provider": string;
    "username": string;
    "personalAccessToken": string;
}

export interface LocationDTO {
    "uri": string;
    "startLine": number;
    "startColumn": number;
    "endLine": number;
    "endColumn": number;
    "snippet": string;
    "snippetStartLine": number;
    "snippetOrigin": string;
    "snippetStatus": string;
}

export interface RunSummaryDTO {
    "index": number;
    "name": string;
    "toolName": string;
    "findingCount": number;
}

export interface SARIFDocumentDTO {
    "documentId": string;
    "fileName": string;
    "sourcePath": string;
    "version": string;
    "findingCount": number;
    "runs": RunSummaryDTO[] | null;
    "findings": FindingDTO[] | null;
    "snippetSummary": SnippetSummaryDTO;
}

export interface SnippetSummaryDTO {
    "generated": number;
    "embedded": number;
    "unavailable": number;
}

export interface SourceSelectionDTO {
    "kind": string;
    "location": string;
    "contextLines": number;
    "gitAuthentication": GitAuthenticationDTO;
}

export interface ThreadFlowDTO {
    "id": string;
    "message": string;
    "steps": CodeFlowStepDTO[] | null;
}
