// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExportSARIF(documentID: string, destination: string, reviews: $models.FindingReview[] | null): $CancellablePromise<void> {
    return $Call.ByID(478487231, documentID, destination, reviews);
}

export function LoadSARIF(path: string, source: $models.SourceSelectionDTO): $CancellablePromise<$models.SARIFDocumentDTO> {
    return $Call.ByID(3609641173, path, source);
}
